apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  labels:
    app: python-api  # Label used for selectors
spec:
  replicas: 2        # Number of pod instances
  selector:
    matchLabels:
      app: python-api  # Must match pod template labels
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: docker.io/iradics1974/python-api:latest  # Docker image to deploy
          imagePullPolicy: Always  # Always pull newest image tag
          ports:
            - containerPort: 5000  # Your Flask app listens on this port

