apiVersion: v1
kind: Service
metadata:
  name: python-api
spec:
  type: NodePort                 # Expose on Minikube IP
  selector:
    app: python-api              # Must match pod labels
  ports:
    - port: 80                   # Service port
      targetPort: 5000           # Flask internal port
     # nodePort: 30080            # External Minikube port

